### ISSUE TITLE
testing main with testing.M?

### ISSUE THREAD

**Issue by TimothyStiles** [allyourbasepair/allbase#17]
@Koeng101 

Noticed this during my last refactor. Is this test necessary and does it need to be a `main` test? The docker-test dependency is pretty iffy and I'm not sure why it's needed.

https://github.com/allyourbasepair/allbase/blob/31c8a4f9a17b393fabf216b946530bc5e4aaf26b/models/models_test.go#L27

**Comment by Koeng101** [comment]
`m *testing.M` will basically run before all other tests. It is mostly to set up the database + sql connection which all of the other tests use. 

The docker-test dependency is only there for when we integrate litestream + minio. It was leftover from when I was hacking things together and thought we would need earlier. We probably will eventually need it, but right now it does slow down the tests by a bit.

**Comment by Koeng101** [comment]
@TimothyStiles Can we close this issue?
