### ISSUE TITLE
Ftp sites

### ISSUE THREAD

**Issue by Koeng101** [allyourbasepair/allbase#18]
Rhea: 
https://ftp.expasy.org/databases/rhea/rdf/rhea.rdf.gz

Rhea TSV sprot:
https://ftp.expasy.org/databases/rhea/tsv/rhea2uniprot%5Fsprot.tsv

Rhea TSV trembl:
https://ftp.expasy.org/databases/rhea/tsv/rhea2uniprot%5Ftrembl.tsv.gz

Uniprot sprot:
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz

Uniprot trembl:
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.xml.gz

**Comment by TimothyStiles** [comment]
Sanity check, I'm assuming you don't leave the https prefix in there correct @Koeng101?

**Comment by Koeng101** [comment]
Sanity check failed. You can leave the https prefixes :)

**Comment by isaacguerreir** [comment]
Thanks, @Koeng101! I will try later to see if I could take some metadata information using the Stat function from **[GoFTP package](https://github.com/secsy/goftp)** . The ftp server choose if the users, or what kind of user, could access those types of information about the files.

**Comment by TimothyStiles** [comment]
This has all been integrated as of merging #21. Closing!
